name: Bump Homebrew Formula (manual)

on:
  workflow_dispatch:
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Get latest version
        id: extract-latest-version
        run: |
          git fetch --tags
          echo "latest-tag-name=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT

      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: homebrew-tests
          formula-path: homebrew-tests.rb
          homebrew-tap: olets/homebrew-tap
          download-url: https://github.com/olets/homebrew-tests.git
          tag-name: ${{ steps.extract-latest-version.outputs.latest-tag-name }}
          commit-message: |
            feat({{formulaName}}): publish {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}