name: Bump Homebrew Formula (manual)

on:
  workflow_dispatch:
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Extract version
        id: extract-version
        # Strip a string prefix from the git tag name:
        run: |
          echo "tag-name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Get latest version
        id: Extract-latest-version
        # Strip a string prefix from the git tag name:
        run: |
          git fetch --tags
          git fetch --prune --unshallow || true
          echo "latest-tag-name=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT

      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: homebrew-tests
          formula-path: homebrew-tests.rb
          homebrew-tap: olets/homebrew-tap
          download-url: https://github.com/olets/homebrew-tests.git
          tag-name: ${{ steps.extract-latest-version.outputs.latest-tag-name }}
          commit-message: |
            feat({{formulaName}}): publish {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}