name: Get Latest Release
on:
  workflow_dispatch:
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Latest release
        uses: thebritican/fetch-latest-release@v1
        id: latest_release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: echo ${{ steps.latest_release.outputs.tag_name }}
