name: Get Latest Release
on:
  workflow_dispatch:
jobs:
  get:
    runs-on: ubuntu-latest
    # example from https://github.com/reloc8/action-latest-release-version
    steps:

      - uses: actions/checkout@v2

      - name: Fetch latest release version
        id: fetch-latest-release
        uses: reloc8/action-latest-release-version@1.0.0

      - name: Test
        run: echo ${{ steps.fetch-latest-release.outputs.latest-release }}
