name: Get Latest Release
on:
  workflow_dispatch:
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Latest release
        uses: pozetroninc/github-action-get-latest-release@master
        id: latest_release
        with:
          excludes: prerelease, draft
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: echo ${{ steps.latest_release.outputs.release }}
