name: Get Latest Release
on:
  workflow_dispatch:
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest version
        uses: actions/checkout@v4
        id: extract-latest-version
        run: |
          git fetch --tags
          git fetch --prune --unshallow || true
          echo "latest-tag-name=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT

      # - name: Fetch latest release version
      #   id: fetch-latest-release
      #   uses: reloc8/action-latest-release-version@1.0.0

      - name: Test
        run: echo ${{ steps.extract-latest-version.outputs.latest-tag-name }}
