name: Get Latest Release
on:
  workflow_dispatch:
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Latest release
        uses: rez0n/actions-github-release@main
        id: latest_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: echo ${{ steps.latest_release.outputs.release }}
